# Generated by Django 6.1 on 2026-09-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loraApi', '0024_deletionrecord_receipt_details'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deletionrecord',
            index=models.Index(fields=['status', 'timestamp'], name='loraApi_del_status_232578_idx'),
        ),
        migrations.AddIndex(
            model_name='deletionrecord',
            index=models.Index(fields=['status', 'confirmation_timestamp'], name='loraApi_del_status_9407ca_idx'),
        ),
        migrations.AddIndex(
            model_name='productcatalog',
            index=models.Index(fields=['branch', 'branch_confirmed'], name='loraApi_pro_branch_1bb137_idx'),
        ),
        migrations.AddIndex(
            model_name='productcatalog',
            index=models.Index(fields=['branch', 'product_name'], name='loraApi_pro_branch_7f21ff_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='loraApi_sto_created_0ed95c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['branch', 'created_at'], name='loraApi_sto_branch_db7596_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['branch', 'created_at'], name='loraApi_sto_branch_1befb9_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['branch', 'product_id', 'created_at'], name='loraApi_sto_branch_bcff0c_idx'),
        ),
    ]
