# Generated by Django 6.1 on 2026-09-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loraApi', '0025_deletionrecord_loraapi_del_status_232578_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=255, unique=True)),
                ('device_role', models.CharField(default='Branch PC', max_length=50)),
                ('last_seen', models.DateTimeField()),
            ],
            options={
                'ordering': ['branch'],
                'indexes': [models.Index(fields=['last_seen'], name='loraApi_bra_last_se_0c9c58_idx')],
            },
        ),
    ]
