# Generated by Django 6.1 on 2026-09-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loraApi', '0029_multiple_daily_sales_report_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=255)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(blank=True, default='', max_length=250)),
                ('requested_by', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['requested_at'],
                'indexes': [models.Index(fields=['branch', 'status', 'updated_at'], name='loraApi_pro_branch_c3d8a5_idx')],
            },
        ),
    ]
